/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Gestor;
import Modelo.Persona;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HugoFDZ
 */
public class MainWindow extends javax.swing.JFrame {

    Color colorTexto = new Color(241, 255, 231);
    Icon icon = new ImageIcon(getClass().getResource("/Media/IconBall.png"));

    public MainWindow() {
        initComponents();

        //Tabla para ver la plantilla de futbol actual
        String[] columnas = {"Nombre", "Apellido", "Rol", "DNI"};
        //Creo el modelo que luego metere en la tabla
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

        //Relleno el modelo con las personas que tiene la listaPersonas
        for (Persona persona : Gestor.getInstancia().getListaPersonas()) {
            modelo.addRow(new Object[]{persona.getNombre(), persona.getApellido(), persona.getClass().getSimpleName(), persona.getDni()});
        }

        //Asigno el modelo a la tabla
        TablaContenidoPlantilla.setModel(modelo);
        //Que no sea clickable ya que la tabla del home quiero que sea solo vista
        TablaContenidoPlantilla.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRaiz = new javax.swing.JPanel();
        HomeWindow = new javax.swing.JPanel();
        Text_Titulo = new javax.swing.JLabel();
        Separador = new javax.swing.JSeparator();
        BtnGestionarPlantilla = new javax.swing.JButton();
        BtnJugarPartido = new javax.swing.JButton();
        BtnGastos = new javax.swing.JButton();
        BtnImprimir = new javax.swing.JButton();
        Separador1 = new javax.swing.JSeparator();
        Panel_RightSide = new javax.swing.JPanel();
        Text_PlantillaActual = new javax.swing.JLabel();
        PanelPlantilla = new javax.swing.JScrollPane();
        TablaContenidoPlantilla = new javax.swing.JTable();
        GestionWindow = new javax.swing.JPanel();
        BarraTop = new javax.swing.JPanel();
        BtnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelRaiz.setLayout(new java.awt.CardLayout());

        HomeWindow.setBackground(new java.awt.Color(59, 185, 122));
        HomeWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HomeWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text_Titulo.setFont(new java.awt.Font("Poppins SemiBold", 1, 56)); // NOI18N
        Text_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Text_Titulo.setText("¡Gestiona tu club!");
        HomeWindow.add(Text_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 570, 60));

        Separador.setForeground(new java.awt.Color(255, 255, 255));
        HomeWindow.add(Separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 610, 20));

        BtnGestionarPlantilla.setBackground(new java.awt.Color(59, 185, 122));
        BtnGestionarPlantilla.setFont(new java.awt.Font("Poppins SemiBold", 1, 36)); // NOI18N
        BtnGestionarPlantilla.setForeground(new java.awt.Color(241, 255, 231));
        BtnGestionarPlantilla.setText("Gestionar plantilla");
        BtnGestionarPlantilla.setBorder(null);
        BtnGestionarPlantilla.setContentAreaFilled(false);
        BtnGestionarPlantilla.setFocusPainted(false);
        BtnGestionarPlantilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnGestionarPlantillaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnGestionarPlantillaMouseExited(evt);
            }
        });
        BtnGestionarPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGestionarPlantillaActionPerformed(evt);
            }
        });
        HomeWindow.add(BtnGestionarPlantilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        BtnJugarPartido.setBackground(new java.awt.Color(59, 185, 122));
        BtnJugarPartido.setFont(new java.awt.Font("Poppins SemiBold", 1, 36)); // NOI18N
        BtnJugarPartido.setForeground(new java.awt.Color(241, 255, 231));
        BtnJugarPartido.setText("Jugar partido");
        BtnJugarPartido.setBorder(null);
        BtnJugarPartido.setContentAreaFilled(false);
        BtnJugarPartido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnJugarPartidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnJugarPartidoMouseExited(evt);
            }
        });
        BtnJugarPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJugarPartidoActionPerformed(evt);
            }
        });
        HomeWindow.add(BtnJugarPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        BtnGastos.setBackground(new java.awt.Color(59, 185, 122));
        BtnGastos.setFont(new java.awt.Font("Poppins SemiBold", 1, 36)); // NOI18N
        BtnGastos.setForeground(new java.awt.Color(241, 255, 231));
        BtnGastos.setText("Gastos");
        BtnGastos.setBorder(null);
        BtnGastos.setContentAreaFilled(false);
        BtnGastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnGastosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnGastosMouseExited(evt);
            }
        });
        BtnGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGastosActionPerformed(evt);
            }
        });
        HomeWindow.add(BtnGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        BtnImprimir.setBackground(new java.awt.Color(59, 185, 122));
        BtnImprimir.setFont(new java.awt.Font("Poppins SemiBold", 1, 36)); // NOI18N
        BtnImprimir.setForeground(new java.awt.Color(241, 255, 231));
        BtnImprimir.setText("Imprimir");
        BtnImprimir.setBorder(null);
        BtnImprimir.setContentAreaFilled(false);
        BtnImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnImprimirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnImprimirMouseExited(evt);
            }
        });
        BtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImprimirActionPerformed(evt);
            }
        });
        HomeWindow.add(BtnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, -1));

        Separador1.setForeground(new java.awt.Color(255, 255, 255));
        HomeWindow.add(Separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 610, 20));

        Panel_RightSide.setBackground(new java.awt.Color(50, 162, 135));
        Panel_RightSide.setForeground(new java.awt.Color(50, 162, 135));

        Text_PlantillaActual.setFont(new java.awt.Font("Poppins SemiBold", 1, 24)); // NOI18N
        Text_PlantillaActual.setForeground(new java.awt.Color(255, 255, 255));
        Text_PlantillaActual.setText("Plantilla actual");

        PanelPlantilla.setBackground(new java.awt.Color(50, 162, 135));
        PanelPlantilla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelPlantilla.setForeground(new java.awt.Color(50, 162, 135));
        PanelPlantilla.setToolTipText("");
        PanelPlantilla.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N

        TablaContenidoPlantilla.setBackground(new java.awt.Color(50, 162, 135));
        TablaContenidoPlantilla.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        TablaContenidoPlantilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaContenidoPlantilla.setGridColor(new java.awt.Color(169, 253, 172));
        TablaContenidoPlantilla.setSelectionBackground(new java.awt.Color(255, 255, 255));
        TablaContenidoPlantilla.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TablaContenidoPlantilla.setShowGrid(false);
        TablaContenidoPlantilla.setShowHorizontalLines(true);
        PanelPlantilla.setViewportView(TablaContenidoPlantilla);

        javax.swing.GroupLayout Panel_RightSideLayout = new javax.swing.GroupLayout(Panel_RightSide);
        Panel_RightSide.setLayout(Panel_RightSideLayout);
        Panel_RightSideLayout.setHorizontalGroup(
            Panel_RightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RightSideLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Text_PlantillaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(Panel_RightSideLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(PanelPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        Panel_RightSideLayout.setVerticalGroup(
            Panel_RightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RightSideLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Text_PlantillaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        HomeWindow.add(Panel_RightSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 350, 600));

        PanelRaiz.add(HomeWindow, "card2");

        GestionWindow.setBackground(new java.awt.Color(59, 185, 122));
        GestionWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraTop.setBackground(new java.awt.Color(50, 162, 135));

        BtnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/home.png"))); // NOI18N
        BtnHome.setBorder(null);
        BtnHome.setBorderPainted(false);
        BtnHome.setContentAreaFilled(false);
        BtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BarraTopLayout = new javax.swing.GroupLayout(BarraTop);
        BarraTop.setLayout(BarraTopLayout);
        BarraTopLayout.setHorizontalGroup(
            BarraTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraTopLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(BtnHome)
                .addContainerGap(886, Short.MAX_VALUE))
        );
        BarraTopLayout.setVerticalGroup(
            BarraTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraTopLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(BtnHome)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        GestionWindow.add(BarraTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelRaiz.add(GestionWindow, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGestionarPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGestionarPlantillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGestionarPlantillaActionPerformed

    private void BtnJugarPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJugarPartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnJugarPartidoActionPerformed

    private void BtnGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGastosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGastosActionPerformed

    private void BtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnImprimirActionPerformed

    private void BtnGestionarPlantillaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGestionarPlantillaMouseEntered
        stylishButtonEnter(BtnGestionarPlantilla);
    }//GEN-LAST:event_BtnGestionarPlantillaMouseEntered

    private void BtnJugarPartidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnJugarPartidoMouseEntered
        stylishButtonEnter(BtnJugarPartido);
    }//GEN-LAST:event_BtnJugarPartidoMouseEntered

    private void BtnGastosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGastosMouseEntered
        stylishButtonEnter(BtnGastos);
    }//GEN-LAST:event_BtnGastosMouseEntered

    private void BtnImprimirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnImprimirMouseEntered
        stylishButtonEnter(BtnImprimir);
    }//GEN-LAST:event_BtnImprimirMouseEntered

    private void BtnGestionarPlantillaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGestionarPlantillaMouseExited
        stylishButtonExit(BtnGestionarPlantilla);
    }//GEN-LAST:event_BtnGestionarPlantillaMouseExited

    private void BtnJugarPartidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnJugarPartidoMouseExited
        stylishButtonExit(BtnJugarPartido);
    }//GEN-LAST:event_BtnJugarPartidoMouseExited

    private void BtnGastosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGastosMouseExited
        stylishButtonExit(BtnGastos);
    }//GEN-LAST:event_BtnGastosMouseExited

    private void BtnImprimirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnImprimirMouseExited
        stylishButtonExit(BtnImprimir);
    }//GEN-LAST:event_BtnImprimirMouseExited

    private void BtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnHomeActionPerformed

    private void stylishButtonEnter(JButton boton) {
        boton.setForeground(Color.white);
        boton.setIcon(icon);
    }

    private void stylishButtonExit(JButton boton) {
        boton.setForeground(colorTexto);
        boton.setIcon(null);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraTop;
    private javax.swing.JButton BtnGastos;
    private javax.swing.JButton BtnGestionarPlantilla;
    private javax.swing.JButton BtnHome;
    private javax.swing.JButton BtnImprimir;
    private javax.swing.JButton BtnJugarPartido;
    private javax.swing.JPanel GestionWindow;
    private javax.swing.JPanel HomeWindow;
    private javax.swing.JScrollPane PanelPlantilla;
    private javax.swing.JPanel PanelRaiz;
    private javax.swing.JPanel Panel_RightSide;
    private javax.swing.JSeparator Separador;
    private javax.swing.JSeparator Separador1;
    private javax.swing.JTable TablaContenidoPlantilla;
    private javax.swing.JLabel Text_PlantillaActual;
    private javax.swing.JLabel Text_Titulo;
    // End of variables declaration//GEN-END:variables

    public JPanel getHomeWindow() {
        return HomeWindow;
    }

    public JPanel getPanelRaiz() {
        return PanelRaiz;
    }

    public JLabel getText_PlantillaActual() {
        return Text_PlantillaActual;
    }

    public JButton getBtnGastos() {
        return BtnGastos;
    }

    public JButton getBtnGestionarPlantilla() {
        return BtnGestionarPlantilla;
    }

    public JButton getBtnImprimir() {
        return BtnImprimir;
    }

    public JButton getBtnJugarPartido() {
        return BtnJugarPartido;
    }

    public JScrollPane getPanelPlantilla() {
        return PanelPlantilla;
    }

    public JTable getTablaContenidoPlantilla() {
        return TablaContenidoPlantilla;
    }

}
