/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Gestor;
import Modelo.Persona;
import Modelo.Demarcacion;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import Modelo.Especialidad;
import Modelo.Puesto;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HugoFDZ
 */
public class MainWindow extends javax.swing.JFrame {

    Color colorTexto = new Color(241, 255, 231);
    Color backgroundColor = new Color(59, 185, 122);
    Icon icon = new ImageIcon(getClass().getResource("/Media/IconBall.png"));

    public MainWindow() {
        initComponents();

        //Tabla para ver la plantilla de futbol actual
        String[] columnas = {"Nombre", "Apellido", "Rol", "DNI"};
        //Creo el modelo que luego metere en la tabla
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            //Le sobreescribo el metodo para que el usuario no pueda editar las celdas de las tablas
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Desactiva la edición de celdas
            }
        };

        //Relleno el modelo con las personas que tiene la listaPersonas
        for (Persona persona : Gestor.getInstancia().getListaPersonas()) {
            modelo.addRow(new String[]{persona.getNombre(), persona.getApellido(), persona.getClass().getSimpleName(), persona.getDni()});
        }

        //Asigno el modelo a las tablas
        TablaContenidoPlantilla.setModel(modelo);
        TablaGestionPersonas.setModel(modelo);
        //Que no sea clickable ya que la tabla del home quiero que sea solo vista
        TablaContenidoPlantilla.setEnabled(false);

        //Creo el CardLayout para cambiar entre ventanas
        PanelRaiz.setLayout(new CardLayout());
        PanelRaiz.add(HomeWindow, "homeWindow");
        PanelRaiz.add(GestionWindow, "gestionWindow");
        PanelRaiz.add(DarDeAltaWindow, "darDeAltaWindow");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRaiz = new javax.swing.JPanel();
        HomeWindow = new javax.swing.JPanel();
        Text_Titulo = new javax.swing.JLabel();
        Separador = new javax.swing.JSeparator();
        BtnGestionarPlantilla = new javax.swing.JButton();
        BtnJugarPartido = new javax.swing.JButton();
        BtnGastos = new javax.swing.JButton();
        BtnImprimir = new javax.swing.JButton();
        Separador1 = new javax.swing.JSeparator();
        Panel_RightSide = new javax.swing.JPanel();
        Text_PlantillaActual = new javax.swing.JLabel();
        PanelPlantilla = new javax.swing.JScrollPane();
        TablaContenidoPlantilla = new javax.swing.JTable();
        GestionWindow = new javax.swing.JPanel();
        BtnDarDeAltaPersona = new javax.swing.JButton();
        BtnEliminarPersona = new javax.swing.JButton();
        BtnModificarDatos = new javax.swing.JButton();
        BarraTop = new javax.swing.JPanel();
        BtnHome = new javax.swing.JButton();
        PanelGestionPersonas = new javax.swing.JScrollPane();
        TablaGestionPersonas = new javax.swing.JTable();
        DarDeAltaWindow = new javax.swing.JPanel();
        Text_DarDeAlta = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TabbedDarDeAlta = new javax.swing.JTabbedPane();
        PanelAltaJugador = new javax.swing.JPanel();
        TextoAltaJugadorNombre = new javax.swing.JLabel();
        InputAltaJugadorNombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        TextoAltaJugadorApellido = new javax.swing.JLabel();
        InputAltaJugadorApellido = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        TextoAltaJugadorTelefono = new javax.swing.JLabel();
        InputAltaJugadorTelefono = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        TextoAltaJugadorEdad = new javax.swing.JLabel();
        InputAltaJugadorEdad = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        TextoAltaJugadorValor = new javax.swing.JLabel();
        InputAltaJugadorValor = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        TextoAltaJugadorDNI = new javax.swing.JLabel();
        InputAltaJugadorDNI = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        BtnCrearJugador = new javax.swing.JButton();
        TextoAltaJugadorDemarcacion = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        ComBoxDemarcacion = new javax.swing.JComboBox<>();
        TextoAltaJugadorEstadoFisico = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        ToggleEstadoFisico = new javax.swing.JToggleButton();
        PanelAltaTecnico = new javax.swing.JPanel();
        TextoAltaTecnicoNombre = new javax.swing.JLabel();
        InputAltaTecnicoNombre = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        TextoAltaTecnicoApellido = new javax.swing.JLabel();
        InputAltaTecnicoApellido = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        TextoAltaTecnicoTelefono = new javax.swing.JLabel();
        InputAltaTecnicoTelefono = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        TextoAltaTecnicoDNI = new javax.swing.JLabel();
        InputAltaTecnicoDNI = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        TextoAltaJugadorValor1 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        TextoAltaJugadorDNI1 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        BtnCrearTecnico = new javax.swing.JButton();
        ComboBoxTecnicoEspecialidad = new javax.swing.JComboBox<>();
        ComboBoxTecnicoPuesto = new javax.swing.JComboBox<>();
        PanelAltaDirectivo = new javax.swing.JPanel();
        TextoAltaDirectivoNombre = new javax.swing.JLabel();
        InputAltaDirectivoCargo = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        TextoAltaDirectivoApellido = new javax.swing.JLabel();
        InputAltaDirectivoApellido = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        TextoAltaDirectivoTelefono = new javax.swing.JLabel();
        InputAltaDirectivoTelefono = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        TextoAltaDirectivoDNI = new javax.swing.JLabel();
        InputAltaDirectivoDNI = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        BtnCrearDirectivo = new javax.swing.JButton();
        TextoAltaDirectivoCargo = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        InputAltaDirectivoNombre = new javax.swing.JTextField();
        BtnDarDeAltaAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelRaiz.setLayout(new java.awt.CardLayout());

        HomeWindow.setBackground(new java.awt.Color(59, 185, 122));
        HomeWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HomeWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text_Titulo.setFont(new java.awt.Font("Poppins SemiBold", 1, 56)); // NOI18N
        Text_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Text_Titulo.setText("¡Gestiona tu club!");
        HomeWindow.add(Text_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 570, 60));

        Separador.setForeground(new java.awt.Color(255, 255, 255));
        HomeWindow.add(Separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 610, 20));

        BtnGestionarPlantilla.setBackground(new java.awt.Color(59, 185, 122));
        BtnGestionarPlantilla.setFont(new java.awt.Font("Poppins SemiBold", 1, 36)); // NOI18N
        BtnGestionarPlantilla.setForeground(new java.awt.Color(241, 255, 231));
        BtnGestionarPlantilla.setText("Gestionar plantilla");
        BtnGestionarPlantilla.setBorder(null);
        BtnGestionarPlantilla.setContentAreaFilled(false);
        BtnGestionarPlantilla.setFocusPainted(false);
        BtnGestionarPlantilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnGestionarPlantillaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnGestionarPlantillaMouseExited(evt);
            }
        });
        BtnGestionarPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGestionarPlantillaActionPerformed(evt);
            }
        });
        HomeWindow.add(BtnGestionarPlantilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        BtnJugarPartido.setBackground(new java.awt.Color(59, 185, 122));
        BtnJugarPartido.setFont(new java.awt.Font("Poppins SemiBold", 1, 36)); // NOI18N
        BtnJugarPartido.setForeground(new java.awt.Color(241, 255, 231));
        BtnJugarPartido.setText("Jugar partido");
        BtnJugarPartido.setBorder(null);
        BtnJugarPartido.setContentAreaFilled(false);
        BtnJugarPartido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnJugarPartidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnJugarPartidoMouseExited(evt);
            }
        });
        BtnJugarPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJugarPartidoActionPerformed(evt);
            }
        });
        HomeWindow.add(BtnJugarPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        BtnGastos.setBackground(new java.awt.Color(59, 185, 122));
        BtnGastos.setFont(new java.awt.Font("Poppins SemiBold", 1, 36)); // NOI18N
        BtnGastos.setForeground(new java.awt.Color(241, 255, 231));
        BtnGastos.setText("Gastos");
        BtnGastos.setBorder(null);
        BtnGastos.setContentAreaFilled(false);
        BtnGastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnGastosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnGastosMouseExited(evt);
            }
        });
        BtnGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGastosActionPerformed(evt);
            }
        });
        HomeWindow.add(BtnGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        BtnImprimir.setBackground(new java.awt.Color(59, 185, 122));
        BtnImprimir.setFont(new java.awt.Font("Poppins SemiBold", 1, 36)); // NOI18N
        BtnImprimir.setForeground(new java.awt.Color(241, 255, 231));
        BtnImprimir.setText("Imprimir");
        BtnImprimir.setBorder(null);
        BtnImprimir.setContentAreaFilled(false);
        BtnImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnImprimirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnImprimirMouseExited(evt);
            }
        });
        BtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImprimirActionPerformed(evt);
            }
        });
        HomeWindow.add(BtnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, -1));

        Separador1.setForeground(new java.awt.Color(255, 255, 255));
        HomeWindow.add(Separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 610, 20));

        Panel_RightSide.setBackground(new java.awt.Color(50, 162, 135));
        Panel_RightSide.setForeground(new java.awt.Color(50, 162, 135));

        Text_PlantillaActual.setFont(new java.awt.Font("Poppins SemiBold", 1, 24)); // NOI18N
        Text_PlantillaActual.setForeground(new java.awt.Color(255, 255, 255));
        Text_PlantillaActual.setText("Plantilla actual");

        PanelPlantilla.setBackground(new java.awt.Color(50, 162, 135));
        PanelPlantilla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelPlantilla.setForeground(new java.awt.Color(50, 162, 135));
        PanelPlantilla.setToolTipText("");
        PanelPlantilla.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N

        TablaContenidoPlantilla.setBackground(new java.awt.Color(50, 162, 135));
        TablaContenidoPlantilla.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        TablaContenidoPlantilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaContenidoPlantilla.setGridColor(new java.awt.Color(169, 253, 172));
        TablaContenidoPlantilla.setSelectionBackground(new java.awt.Color(255, 255, 255));
        TablaContenidoPlantilla.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TablaContenidoPlantilla.setShowGrid(false);
        TablaContenidoPlantilla.setShowHorizontalLines(true);
        PanelPlantilla.setViewportView(TablaContenidoPlantilla);

        javax.swing.GroupLayout Panel_RightSideLayout = new javax.swing.GroupLayout(Panel_RightSide);
        Panel_RightSide.setLayout(Panel_RightSideLayout);
        Panel_RightSideLayout.setHorizontalGroup(
            Panel_RightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RightSideLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Text_PlantillaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(Panel_RightSideLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(PanelPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        Panel_RightSideLayout.setVerticalGroup(
            Panel_RightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RightSideLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Text_PlantillaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        HomeWindow.add(Panel_RightSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 350, 600));

        PanelRaiz.add(HomeWindow, "card2");

        GestionWindow.setBackground(new java.awt.Color(59, 185, 122));
        GestionWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnDarDeAltaPersona.setText("Dar de alta");
        GestionWindow.add(BtnDarDeAltaPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 150, 70));

        BtnEliminarPersona.setText("Eliminar persona");
        BtnEliminarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarPersonaActionPerformed(evt);
            }
        });
        GestionWindow.add(BtnEliminarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 170, 30));

        BtnModificarDatos.setText("Modificar persona");
        GestionWindow.add(BtnModificarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 150, 80));

        BarraTop.setBackground(new java.awt.Color(50, 162, 135));

        BtnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/home.png"))); // NOI18N
        BtnHome.setBorder(null);
        BtnHome.setBorderPainted(false);
        BtnHome.setContentAreaFilled(false);
        BtnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnHomeMouseExited(evt);
            }
        });
        BtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BarraTopLayout = new javax.swing.GroupLayout(BarraTop);
        BarraTop.setLayout(BarraTopLayout);
        BarraTopLayout.setHorizontalGroup(
            BarraTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraTopLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(BtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(911, Short.MAX_VALUE))
        );
        BarraTopLayout.setVerticalGroup(
            BarraTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        GestionWindow.add(BarraTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 70));

        TablaGestionPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        PanelGestionPersonas.setViewportView(TablaGestionPersonas);

        GestionWindow.add(PanelGestionPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 630, 440));

        PanelRaiz.add(GestionWindow, "card3");

        DarDeAltaWindow.setBackground(new java.awt.Color(59, 185, 122));
        DarDeAltaWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text_DarDeAlta.setFont(new java.awt.Font("Poppins SemiBold", 1, 65)); // NOI18N
        Text_DarDeAlta.setForeground(new java.awt.Color(255, 255, 255));
        Text_DarDeAlta.setText("Dar de alta");
        DarDeAltaWindow.add(Text_DarDeAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        DarDeAltaWindow.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 450, 10));

        TabbedDarDeAlta.setBackground(new java.awt.Color(169, 253, 172));
        TabbedDarDeAlta.setForeground(new java.awt.Color(255, 255, 255));
        TabbedDarDeAlta.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N

        PanelAltaJugador.setBackground(new java.awt.Color(169, 253, 172));
        PanelAltaJugador.setForeground(new java.awt.Color(169, 253, 172));
        PanelAltaJugador.setToolTipText("");

        TextoAltaJugadorNombre.setBackground(new java.awt.Color(255, 255, 255));
        TextoAltaJugadorNombre.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        TextoAltaJugadorNombre.setForeground(new java.awt.Color(255, 255, 255));
        TextoAltaJugadorNombre.setText("Nombre");

        InputAltaJugadorNombre.setBackground(new java.awt.Color(169, 253, 172));
        InputAltaJugadorNombre.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        InputAltaJugadorNombre.setForeground(new java.awt.Color(204, 204, 204));
        InputAltaJugadorNombre.setText("Inserte el nombre...");
        InputAltaJugadorNombre.setBorder(null);
        InputAltaJugadorNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputAltaJugadorNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputAltaJugadorNombreFocusLost(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        TextoAltaJugadorApellido.setBackground(new java.awt.Color(255, 255, 255));
        TextoAltaJugadorApellido.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        TextoAltaJugadorApellido.setForeground(new java.awt.Color(255, 255, 255));
        TextoAltaJugadorApellido.setText("Apellidos");

        InputAltaJugadorApellido.setBackground(new java.awt.Color(169, 253, 172));
        InputAltaJugadorApellido.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        InputAltaJugadorApellido.setForeground(new java.awt.Color(204, 204, 204));
        InputAltaJugadorApellido.setText("Inserte el apellido...");
        InputAltaJugadorApellido.setBorder(null);
        InputAltaJugadorApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputAltaJugadorApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputAltaJugadorApellidoFocusLost(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        TextoAltaJugadorTelefono.setBackground(new java.awt.Color(255, 255, 255));
        TextoAltaJugadorTelefono.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        TextoAltaJugadorTelefono.setForeground(new java.awt.Color(255, 255, 255));
        TextoAltaJugadorTelefono.setText("Teléfono");

        InputAltaJugadorTelefono.setBackground(new java.awt.Color(169, 253, 172));
        InputAltaJugadorTelefono.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        InputAltaJugadorTelefono.setForeground(new java.awt.Color(204, 204, 204));
        InputAltaJugadorTelefono.setText("Inserte el teléfono...");
        InputAltaJugadorTelefono.setBorder(null);
        InputAltaJugadorTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputAltaJugadorTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputAltaJugadorTelefonoFocusLost(evt);
            }
        });
        InputAltaJugadorTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputAltaJugadorTelefonoKeyTyped(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        TextoAltaJugadorEdad.setBackground(new java.awt.Color(255, 255, 255));
        TextoAltaJugadorEdad.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        TextoAltaJugadorEdad.setForeground(new java.awt.Color(255, 255, 255));
        TextoAltaJugadorEdad.setText("Edad");

        InputAltaJugadorEdad.setBackground(new java.awt.Color(169, 253, 172));
        InputAltaJugadorEdad.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        InputAltaJugadorEdad.setForeground(new java.awt.Color(204, 204, 204));
        InputAltaJugadorEdad.setText("Inserte la edad...");
        InputAltaJugadorEdad.setBorder(null);
        InputAltaJugadorEdad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputAltaJugadorEdadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputAltaJugadorEdadFocusLost(evt);
            }
        });
        InputAltaJugadorEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputAltaJugadorEdadKeyTyped(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        TextoAltaJugadorValor.setBackground(new java.awt.Color(255, 255, 255));
        TextoAltaJugadorValor.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        TextoAltaJugadorValor.setForeground(new java.awt.Color(255, 255, 255));
        TextoAltaJugadorValor.setText("Valor de mercado");

        InputAltaJugadorValor.setBackground(new java.awt.Color(169, 253, 172));
        InputAltaJugadorValor.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        InputAltaJugadorValor.setForeground(new java.awt.Color(204, 204, 204));
        InputAltaJugadorValor.setText("Inserte el valor de mercado...");
        InputAltaJugadorValor.setBorder(null);
        InputAltaJugadorValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputAltaJugadorValorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputAltaJugadorValorFocusLost(evt);
            }
        });
        InputAltaJugadorValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputAltaJugadorValorKeyTyped(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));

        TextoAltaJugadorDNI.setBackground(new java.awt.Color(255, 255, 255));
        TextoAltaJugadorDNI.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        TextoAltaJugadorDNI.setForeground(new java.awt.Color(255, 255, 255));
        TextoAltaJugadorDNI.setText("DNI");

        InputAltaJugadorDNI.setBackground(new java.awt.Color(169, 253, 172));
        InputAltaJugadorDNI.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        InputAltaJugadorDNI.setForeground(new java.awt.Color(204, 204, 204));
        InputAltaJugadorDNI.setText("Inserte el DNI...");
        InputAltaJugadorDNI.setBorder(null);
        InputAltaJugadorDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputAltaJugadorDNIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputAltaJugadorDNIFocusLost(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));

        BtnCrearJugador.setBackground(new java.awt.Color(59, 185, 122));
        BtnCrearJugador.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        BtnCrearJugador.setForeground(new java.awt.Color(255, 255, 255));
        BtnCrearJugador.setText("Crear jugador");
        BtnCrearJugador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TextoAltaJugadorDemarcacion.setBackground(new java.awt.Color(255, 255, 255));
        TextoAltaJugadorDemarcacion.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        TextoAltaJugadorDemarcacion.setForeground(new java.awt.Color(255, 255, 255));
        TextoAltaJugadorDemarcacion.setText("Demarcacion");

        jSeparator19.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator19.setForeground(new java.awt.Color(255, 255, 255));

        TextoAltaJugadorEstadoFisico.setBackground(new java.awt.Color(255, 255, 255));
        TextoAltaJugadorEstadoFisico.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        TextoAltaJugadorEstadoFisico.setForeground(new java.awt.Color(255, 255, 255));
        TextoAltaJugadorEstadoFisico.setText("Estado fisico");

        jSeparator20.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator20.setForeground(new java.awt.Color(255, 255, 255));

        ToggleEstadoFisico.setBackground(new java.awt.Color(59, 185, 122));
        ToggleEstadoFisico.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        ToggleEstadoFisico.setForeground(new java.awt.Color(255, 255, 255));
        ToggleEstadoFisico.setText("Saludable");
        ToggleEstadoFisico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ToggleEstadoFisico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ToggleEstadoFisicoMousePressed(evt);
            }
        });
        ToggleEstadoFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleEstadoFisicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAltaJugadorLayout = new javax.swing.GroupLayout(PanelAltaJugador);
        PanelAltaJugador.setLayout(PanelAltaJugadorLayout);
        PanelAltaJugadorLayout.setHorizontalGroup(
            PanelAltaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAltaJugadorLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(PanelAltaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAltaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(PanelAltaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextoAltaJugadorApellido)
                            .addComponent(jSeparator3)
                            .addComponent(InputAltaJugadorApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelAltaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextoAltaJugadorNombre)
                            .addComponent(jSeparator2)
                            .addComponent(InputAltaJugadorNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)))
                    .addGroup(PanelAltaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TextoAltaJugadorTelefono)
                        .addComponent(jSeparator4)
                        .addComponent(InputAltaJugadorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAltaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TextoAltaJugadorEdad)
                        .addComponent(jSeparator5)
                        .addComponent(InputAltaJugadorEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelAltaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAltaJugadorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 406, Short.MAX_VALUE)
                        .addComponent(BtnCrearJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(PanelAltaJugadorLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(PanelAltaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextoAltaJugadorDemarcacion)
                            .addComponent(TextoAltaJugadorValor)
                            .addComponent(jSeparator6)
                            .addComponent(InputAltaJugadorValor)
                            .addComponent(TextoAltaJugadorDNI)
                            .addComponent(jSeparator7)
                            .addComponent(InputAltaJugadorDNI)
                            .addComponent(ComBoxDemarcacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelAltaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoAltaJugadorEstadoFisico)
                            .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ToggleEstadoFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93))))
        );
        PanelAltaJugadorLayout.setVerticalGroup(
            PanelAltaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAltaJugadorLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(PanelAltaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelAltaJugadorLayout.createSequentialGroup()
                        .addComponent(TextoAltaJugadorNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputAltaJugadorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAltaJugadorLayout.createSequentialGroup()
                        .addComponent(TextoAltaJugadorValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputAltaJugadorValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAltaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelAltaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelAltaJugadorLayout.createSequentialGroup()
                            .addComponent(TextoAltaJugadorApellido)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(InputAltaJugadorApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelAltaJugadorLayout.createSequentialGroup()
                            .addComponent(TextoAltaJugadorDNI)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(InputAltaJugadorDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelAltaJugadorLayout.createSequentialGroup()
                        .addComponent(TextoAltaJugadorEstadoFisico)
                        .addGap(5, 5, 5)
                        .addComponent(ToggleEstadoFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PanelAltaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAltaJugadorLayout.createSequentialGroup()
                        .addComponent(TextoAltaJugadorTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputAltaJugadorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelAltaJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAltaJugadorLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextoAltaJugadorEdad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InputAltaJugadorEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAltaJugadorLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(BtnCrearJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))))
                    .addGroup(PanelAltaJugadorLayout.createSequentialGroup()
                        .addComponent(TextoAltaJugadorDemarcacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComBoxDemarcacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        TabbedDarDeAlta.addTab("Jugador", PanelAltaJugador);

        PanelAltaTecnico.setBackground(new java.awt.Color(169, 253, 172));

        TextoAltaTecnicoNombre.setBackground(new java.awt.Color(255, 255, 255));
        TextoAltaTecnicoNombre.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        TextoAltaTecnicoNombre.setForeground(new java.awt.Color(255, 255, 255));
        TextoAltaTecnicoNombre.setText("Nombre");

        InputAltaTecnicoNombre.setBackground(new java.awt.Color(169, 253, 172));
        InputAltaTecnicoNombre.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        InputAltaTecnicoNombre.setForeground(new java.awt.Color(204, 204, 204));
        InputAltaTecnicoNombre.setText("Inserte el nombre...");
        InputAltaTecnicoNombre.setBorder(null);
        InputAltaTecnicoNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputAltaTecnicoNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputAltaTecnicoNombreFocusLost(evt);
            }
        });

        jSeparator12.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));

        TextoAltaTecnicoApellido.setBackground(new java.awt.Color(255, 255, 255));
        TextoAltaTecnicoApellido.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        TextoAltaTecnicoApellido.setForeground(new java.awt.Color(255, 255, 255));
        TextoAltaTecnicoApellido.setText("Apellidos");

        InputAltaTecnicoApellido.setBackground(new java.awt.Color(169, 253, 172));
        InputAltaTecnicoApellido.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        InputAltaTecnicoApellido.setForeground(new java.awt.Color(204, 204, 204));
        InputAltaTecnicoApellido.setText("Inserte el apellido...");
        InputAltaTecnicoApellido.setBorder(null);
        InputAltaTecnicoApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputAltaTecnicoApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputAltaTecnicoApellidoFocusLost(evt);
            }
        });

        jSeparator14.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator14.setForeground(new java.awt.Color(255, 255, 255));

        TextoAltaTecnicoTelefono.setBackground(new java.awt.Color(255, 255, 255));
        TextoAltaTecnicoTelefono.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        TextoAltaTecnicoTelefono.setForeground(new java.awt.Color(255, 255, 255));
        TextoAltaTecnicoTelefono.setText("Teléfono");

        InputAltaTecnicoTelefono.setBackground(new java.awt.Color(169, 253, 172));
        InputAltaTecnicoTelefono.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        InputAltaTecnicoTelefono.setForeground(new java.awt.Color(204, 204, 204));
        InputAltaTecnicoTelefono.setText("Inserte el teléfono...");
        InputAltaTecnicoTelefono.setBorder(null);
        InputAltaTecnicoTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputAltaTecnicoTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputAltaTecnicoTelefonoFocusLost(evt);
            }
        });
        InputAltaTecnicoTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputAltaTecnicoTelefonoKeyTyped(evt);
            }
        });

        jSeparator15.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator15.setForeground(new java.awt.Color(255, 255, 255));

        TextoAltaTecnicoDNI.setBackground(new java.awt.Color(255, 255, 255));
        TextoAltaTecnicoDNI.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        TextoAltaTecnicoDNI.setForeground(new java.awt.Color(255, 255, 255));
        TextoAltaTecnicoDNI.setText("DNI");

        InputAltaTecnicoDNI.setBackground(new java.awt.Color(169, 253, 172));
        InputAltaTecnicoDNI.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        InputAltaTecnicoDNI.setForeground(new java.awt.Color(204, 204, 204));
        InputAltaTecnicoDNI.setText("Inserte el DNI...");
        InputAltaTecnicoDNI.setBorder(null);
        InputAltaTecnicoDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputAltaTecnicoDNIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputAltaTecnicoDNIFocusLost(evt);
            }
        });

        jSeparator16.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator16.setForeground(new java.awt.Color(255, 255, 255));

        TextoAltaJugadorValor1.setBackground(new java.awt.Color(255, 255, 255));
        TextoAltaJugadorValor1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        TextoAltaJugadorValor1.setForeground(new java.awt.Color(255, 255, 255));
        TextoAltaJugadorValor1.setText("Puesto");

        jSeparator17.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator17.setForeground(new java.awt.Color(255, 255, 255));

        TextoAltaJugadorDNI1.setBackground(new java.awt.Color(255, 255, 255));
        TextoAltaJugadorDNI1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        TextoAltaJugadorDNI1.setForeground(new java.awt.Color(255, 255, 255));
        TextoAltaJugadorDNI1.setText("Especialidad");

        jSeparator18.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator18.setForeground(new java.awt.Color(255, 255, 255));

        BtnCrearTecnico.setBackground(new java.awt.Color(59, 185, 122));
        BtnCrearTecnico.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        BtnCrearTecnico.setForeground(new java.awt.Color(255, 255, 255));
        BtnCrearTecnico.setText("Crear técnico");
        BtnCrearTecnico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout PanelAltaTecnicoLayout = new javax.swing.GroupLayout(PanelAltaTecnico);
        PanelAltaTecnico.setLayout(PanelAltaTecnicoLayout);
        PanelAltaTecnicoLayout.setHorizontalGroup(
            PanelAltaTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAltaTecnicoLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(PanelAltaTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAltaTecnicoLayout.createSequentialGroup()
                        .addGroup(PanelAltaTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAltaTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextoAltaTecnicoTelefono)
                                .addComponent(jSeparator15)
                                .addComponent(InputAltaTecnicoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelAltaTecnicoLayout.createSequentialGroup()
                                .addGroup(PanelAltaTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelAltaTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TextoAltaTecnicoApellido)
                                        .addComponent(jSeparator14)
                                        .addComponent(InputAltaTecnicoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelAltaTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TextoAltaTecnicoNombre)
                                        .addComponent(jSeparator12)
                                        .addComponent(InputAltaTecnicoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)))
                                .addGap(107, 107, 107)
                                .addGroup(PanelAltaTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextoAltaJugadorValor1)
                                    .addComponent(jSeparator17, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(TextoAltaJugadorDNI1)
                                    .addComponent(jSeparator18)
                                    .addComponent(ComboBoxTecnicoEspecialidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ComboBoxTecnicoPuesto, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelAltaTecnicoLayout.createSequentialGroup()
                        .addGroup(PanelAltaTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextoAltaTecnicoDNI)
                            .addComponent(jSeparator16)
                            .addComponent(InputAltaTecnicoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 401, Short.MAX_VALUE)
                        .addComponent(BtnCrearTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        PanelAltaTecnicoLayout.setVerticalGroup(
            PanelAltaTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAltaTecnicoLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(PanelAltaTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelAltaTecnicoLayout.createSequentialGroup()
                        .addComponent(TextoAltaTecnicoNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputAltaTecnicoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAltaTecnicoLayout.createSequentialGroup()
                        .addComponent(TextoAltaJugadorValor1)
                        .addGap(9, 9, 9)
                        .addComponent(ComboBoxTecnicoPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAltaTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAltaTecnicoLayout.createSequentialGroup()
                        .addComponent(TextoAltaTecnicoApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputAltaTecnicoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TextoAltaTecnicoTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputAltaTecnicoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelAltaTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAltaTecnicoLayout.createSequentialGroup()
                                .addComponent(TextoAltaTecnicoDNI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(InputAltaTecnicoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BtnCrearTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelAltaTecnicoLayout.createSequentialGroup()
                        .addComponent(TextoAltaJugadorDNI1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboBoxTecnicoEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        TabbedDarDeAlta.addTab("Técnico", PanelAltaTecnico);

        PanelAltaDirectivo.setBackground(new java.awt.Color(169, 253, 172));

        TextoAltaDirectivoNombre.setBackground(new java.awt.Color(255, 255, 255));
        TextoAltaDirectivoNombre.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        TextoAltaDirectivoNombre.setForeground(new java.awt.Color(255, 255, 255));
        TextoAltaDirectivoNombre.setText("Nombre");

        InputAltaDirectivoCargo.setBackground(new java.awt.Color(169, 253, 172));
        InputAltaDirectivoCargo.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        InputAltaDirectivoCargo.setForeground(new java.awt.Color(204, 204, 204));
        InputAltaDirectivoCargo.setText("Inserte el cargo...");
        InputAltaDirectivoCargo.setBorder(null);
        InputAltaDirectivoCargo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputAltaDirectivoCargoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputAltaDirectivoCargoFocusLost(evt);
            }
        });

        jSeparator8.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));

        TextoAltaDirectivoApellido.setBackground(new java.awt.Color(255, 255, 255));
        TextoAltaDirectivoApellido.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        TextoAltaDirectivoApellido.setForeground(new java.awt.Color(255, 255, 255));
        TextoAltaDirectivoApellido.setText("Apellidos");

        InputAltaDirectivoApellido.setBackground(new java.awt.Color(169, 253, 172));
        InputAltaDirectivoApellido.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        InputAltaDirectivoApellido.setForeground(new java.awt.Color(204, 204, 204));
        InputAltaDirectivoApellido.setText("Inserte el apellido...");
        InputAltaDirectivoApellido.setBorder(null);
        InputAltaDirectivoApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputAltaDirectivoApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputAltaDirectivoApellidoFocusLost(evt);
            }
        });

        jSeparator9.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));

        TextoAltaDirectivoTelefono.setBackground(new java.awt.Color(255, 255, 255));
        TextoAltaDirectivoTelefono.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        TextoAltaDirectivoTelefono.setForeground(new java.awt.Color(255, 255, 255));
        TextoAltaDirectivoTelefono.setText("Teléfono");

        InputAltaDirectivoTelefono.setBackground(new java.awt.Color(169, 253, 172));
        InputAltaDirectivoTelefono.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        InputAltaDirectivoTelefono.setForeground(new java.awt.Color(204, 204, 204));
        InputAltaDirectivoTelefono.setText("Inserte el teléfono...");
        InputAltaDirectivoTelefono.setBorder(null);
        InputAltaDirectivoTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputAltaDirectivoTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputAltaDirectivoTelefonoFocusLost(evt);
            }
        });
        InputAltaDirectivoTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputAltaDirectivoTelefonoKeyTyped(evt);
            }
        });

        jSeparator10.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));

        TextoAltaDirectivoDNI.setBackground(new java.awt.Color(255, 255, 255));
        TextoAltaDirectivoDNI.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        TextoAltaDirectivoDNI.setForeground(new java.awt.Color(255, 255, 255));
        TextoAltaDirectivoDNI.setText("DNI");

        InputAltaDirectivoDNI.setBackground(new java.awt.Color(169, 253, 172));
        InputAltaDirectivoDNI.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        InputAltaDirectivoDNI.setForeground(new java.awt.Color(204, 204, 204));
        InputAltaDirectivoDNI.setText("Inserte el DNI...");
        InputAltaDirectivoDNI.setBorder(null);
        InputAltaDirectivoDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputAltaDirectivoDNIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputAltaDirectivoDNIFocusLost(evt);
            }
        });

        jSeparator13.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator13.setForeground(new java.awt.Color(255, 255, 255));

        BtnCrearDirectivo.setBackground(new java.awt.Color(59, 185, 122));
        BtnCrearDirectivo.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        BtnCrearDirectivo.setForeground(new java.awt.Color(255, 255, 255));
        BtnCrearDirectivo.setText("Crear directivo");
        BtnCrearDirectivo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TextoAltaDirectivoCargo.setBackground(new java.awt.Color(255, 255, 255));
        TextoAltaDirectivoCargo.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        TextoAltaDirectivoCargo.setForeground(new java.awt.Color(255, 255, 255));
        TextoAltaDirectivoCargo.setText("Cargo");

        jSeparator11.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));

        InputAltaDirectivoNombre.setBackground(new java.awt.Color(169, 253, 172));
        InputAltaDirectivoNombre.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        InputAltaDirectivoNombre.setForeground(new java.awt.Color(204, 204, 204));
        InputAltaDirectivoNombre.setText("Inserte el nombre...");
        InputAltaDirectivoNombre.setBorder(null);
        InputAltaDirectivoNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputAltaDirectivoNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputAltaDirectivoNombreFocusLost(evt);
            }
        });

        javax.swing.GroupLayout PanelAltaDirectivoLayout = new javax.swing.GroupLayout(PanelAltaDirectivo);
        PanelAltaDirectivo.setLayout(PanelAltaDirectivoLayout);
        PanelAltaDirectivoLayout.setHorizontalGroup(
            PanelAltaDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAltaDirectivoLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(PanelAltaDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAltaDirectivoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnCrearDirectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(PanelAltaDirectivoLayout.createSequentialGroup()
                        .addGroup(PanelAltaDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAltaDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanelAltaDirectivoLayout.createSequentialGroup()
                                    .addComponent(InputAltaDirectivoNombre)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(PanelAltaDirectivoLayout.createSequentialGroup()
                                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(131, 131, 131)))
                            .addGroup(PanelAltaDirectivoLayout.createSequentialGroup()
                                .addGroup(PanelAltaDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelAltaDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(PanelAltaDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TextoAltaDirectivoDNI)
                                            .addComponent(jSeparator13)
                                            .addComponent(InputAltaDirectivoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PanelAltaDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TextoAltaDirectivoTelefono)
                                            .addComponent(jSeparator10)
                                            .addComponent(InputAltaDirectivoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PanelAltaDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(PanelAltaDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TextoAltaDirectivoApellido)
                                            .addComponent(jSeparator9)
                                            .addComponent(InputAltaDirectivoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PanelAltaDirectivoLayout.createSequentialGroup()
                                            .addComponent(TextoAltaDirectivoNombre)
                                            .addGap(143, 143, 143))))
                                .addGap(131, 131, 131)))
                        .addGroup(PanelAltaDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoAltaDirectivoCargo)
                            .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InputAltaDirectivoCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(384, Short.MAX_VALUE))))
        );
        PanelAltaDirectivoLayout.setVerticalGroup(
            PanelAltaDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAltaDirectivoLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(PanelAltaDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelAltaDirectivoLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(TextoAltaDirectivoApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputAltaDirectivoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextoAltaDirectivoTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputAltaDirectivoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelAltaDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAltaDirectivoLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(BtnCrearDirectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelAltaDirectivoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextoAltaDirectivoDNI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InputAltaDirectivoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelAltaDirectivoLayout.createSequentialGroup()
                        .addGroup(PanelAltaDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoAltaDirectivoNombre)
                            .addComponent(TextoAltaDirectivoCargo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelAltaDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputAltaDirectivoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InputAltaDirectivoCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelAltaDirectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        TabbedDarDeAlta.addTab("Directivo", PanelAltaDirectivo);

        DarDeAltaWindow.add(TabbedDarDeAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1000, 480));

        BtnDarDeAltaAtras.setBackground(new java.awt.Color(59, 185, 122));
        BtnDarDeAltaAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/arrow.png"))); // NOI18N
        BtnDarDeAltaAtras.setBorder(null);
        DarDeAltaWindow.add(BtnDarDeAltaAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 60, 60));

        PanelRaiz.add(DarDeAltaWindow, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGestionarPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGestionarPlantillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGestionarPlantillaActionPerformed

    private void BtnJugarPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJugarPartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnJugarPartidoActionPerformed

    private void BtnGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGastosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGastosActionPerformed

    private void BtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnImprimirActionPerformed

    private void BtnGestionarPlantillaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGestionarPlantillaMouseEntered
        stylishButtonEnter(BtnGestionarPlantilla, icon);
    }//GEN-LAST:event_BtnGestionarPlantillaMouseEntered

    private void BtnJugarPartidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnJugarPartidoMouseEntered
        stylishButtonEnter(BtnJugarPartido, icon);
    }//GEN-LAST:event_BtnJugarPartidoMouseEntered

    private void BtnGastosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGastosMouseEntered
        stylishButtonEnter(BtnGastos, icon);
    }//GEN-LAST:event_BtnGastosMouseEntered

    private void BtnImprimirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnImprimirMouseEntered
        stylishButtonEnter(BtnImprimir, icon);
    }//GEN-LAST:event_BtnImprimirMouseEntered

    private void BtnGestionarPlantillaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGestionarPlantillaMouseExited
        stylishButtonExit(BtnGestionarPlantilla);
    }//GEN-LAST:event_BtnGestionarPlantillaMouseExited

    private void BtnJugarPartidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnJugarPartidoMouseExited
        stylishButtonExit(BtnJugarPartido);
    }//GEN-LAST:event_BtnJugarPartidoMouseExited

    private void BtnGastosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGastosMouseExited
        stylishButtonExit(BtnGastos);
    }//GEN-LAST:event_BtnGastosMouseExited

    private void BtnImprimirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnImprimirMouseExited
        stylishButtonExit(BtnImprimir);
    }//GEN-LAST:event_BtnImprimirMouseExited

    private void BtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnHomeActionPerformed

    private void BtnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHomeMouseEntered

    }//GEN-LAST:event_BtnHomeMouseEntered

    private void BtnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHomeMouseExited

    }//GEN-LAST:event_BtnHomeMouseExited

    private void BtnEliminarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEliminarPersonaActionPerformed

    private void ToggleEstadoFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleEstadoFisicoActionPerformed
        if (ToggleEstadoFisico.isSelected() == true) {
            ToggleEstadoFisico.setContentAreaFilled(false);
            ToggleEstadoFisico.setOpaque(true);
            ToggleEstadoFisico.setBackground(Color.red);
            ToggleEstadoFisico.setText("Lesionado");
        } else {
            ToggleEstadoFisico.setContentAreaFilled(false);
            ToggleEstadoFisico.setOpaque(true);
            ToggleEstadoFisico.setBackground(backgroundColor);
            ToggleEstadoFisico.setText("Saludable");
        }

    }//GEN-LAST:event_ToggleEstadoFisicoActionPerformed

    private void ToggleEstadoFisicoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToggleEstadoFisicoMousePressed

    }//GEN-LAST:event_ToggleEstadoFisicoMousePressed

    private void InputAltaJugadorTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputAltaJugadorTelefonoKeyTyped
        forzarSoloNumero(evt);
    }//GEN-LAST:event_InputAltaJugadorTelefonoKeyTyped

    private void InputAltaJugadorEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputAltaJugadorEdadKeyTyped
        forzarSoloNumero(evt);
    }//GEN-LAST:event_InputAltaJugadorEdadKeyTyped

    private void InputAltaJugadorValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputAltaJugadorValorKeyTyped
        forzarSoloNumero(evt);
    }//GEN-LAST:event_InputAltaJugadorValorKeyTyped

    private void InputAltaTecnicoTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputAltaTecnicoTelefonoKeyTyped
        forzarSoloNumero(evt);
    }//GEN-LAST:event_InputAltaTecnicoTelefonoKeyTyped

    private void InputAltaDirectivoTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputAltaDirectivoTelefonoKeyTyped
        forzarSoloNumero(evt);
    }//GEN-LAST:event_InputAltaDirectivoTelefonoKeyTyped

    private void InputAltaJugadorNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaJugadorNombreFocusGained
        GainFocusStylishTextInput(InputAltaJugadorNombre);
    }//GEN-LAST:event_InputAltaJugadorNombreFocusGained

    private void InputAltaJugadorNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaJugadorNombreFocusLost
        LostFocusStylishTextInput(InputAltaJugadorNombre, "Inserte el nombre...");
    }//GEN-LAST:event_InputAltaJugadorNombreFocusLost

    private void InputAltaJugadorApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaJugadorApellidoFocusGained
        GainFocusStylishTextInput(InputAltaJugadorApellido);
    }//GEN-LAST:event_InputAltaJugadorApellidoFocusGained

    private void InputAltaJugadorApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaJugadorApellidoFocusLost
        LostFocusStylishTextInput(InputAltaJugadorApellido, "Inserte el apellido...");
    }//GEN-LAST:event_InputAltaJugadorApellidoFocusLost

    private void InputAltaJugadorTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaJugadorTelefonoFocusGained
        GainFocusStylishTextInput(InputAltaJugadorTelefono);
    }//GEN-LAST:event_InputAltaJugadorTelefonoFocusGained

    private void InputAltaJugadorTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaJugadorTelefonoFocusLost
        LostFocusStylishTextInput(InputAltaJugadorTelefono, "Inserte el telefono...");
    }//GEN-LAST:event_InputAltaJugadorTelefonoFocusLost

    private void InputAltaTecnicoNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaTecnicoNombreFocusGained
        GainFocusStylishTextInput(InputAltaTecnicoNombre);
    }//GEN-LAST:event_InputAltaTecnicoNombreFocusGained

    private void InputAltaTecnicoNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaTecnicoNombreFocusLost
        LostFocusStylishTextInput(InputAltaTecnicoNombre, "Inserte el nombre...");
    }//GEN-LAST:event_InputAltaTecnicoNombreFocusLost

    private void InputAltaDirectivoNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaDirectivoNombreFocusGained
        GainFocusStylishTextInput(InputAltaDirectivoNombre);
    }//GEN-LAST:event_InputAltaDirectivoNombreFocusGained

    private void InputAltaDirectivoNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaDirectivoNombreFocusLost
        LostFocusStylishTextInput(InputAltaDirectivoNombre, "Inserte el nombre...");
    }//GEN-LAST:event_InputAltaDirectivoNombreFocusLost

    private void InputAltaJugadorEdadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaJugadorEdadFocusGained
        GainFocusStylishTextInput(InputAltaJugadorEdad);
    }//GEN-LAST:event_InputAltaJugadorEdadFocusGained

    private void InputAltaJugadorEdadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaJugadorEdadFocusLost
        LostFocusStylishTextInput(InputAltaJugadorEdad, "Inserte la edad...");
    }//GEN-LAST:event_InputAltaJugadorEdadFocusLost

    private void InputAltaJugadorValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaJugadorValorFocusGained
        GainFocusStylishTextInput(InputAltaJugadorValor);
    }//GEN-LAST:event_InputAltaJugadorValorFocusGained

    private void InputAltaJugadorValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaJugadorValorFocusLost
        LostFocusStylishTextInput(InputAltaJugadorValor, "Inserte el valor...");
    }//GEN-LAST:event_InputAltaJugadorValorFocusLost

    private void InputAltaTecnicoApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaTecnicoApellidoFocusGained
        GainFocusStylishTextInput(InputAltaTecnicoApellido);
    }//GEN-LAST:event_InputAltaTecnicoApellidoFocusGained

    private void InputAltaTecnicoApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaTecnicoApellidoFocusLost
        LostFocusStylishTextInput(InputAltaTecnicoApellido, "Inserte el apellido...");
    }//GEN-LAST:event_InputAltaTecnicoApellidoFocusLost

    private void InputAltaTecnicoTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaTecnicoTelefonoFocusGained
        GainFocusStylishTextInput(InputAltaTecnicoTelefono);
    }//GEN-LAST:event_InputAltaTecnicoTelefonoFocusGained

    private void InputAltaTecnicoTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaTecnicoTelefonoFocusLost
        LostFocusStylishTextInput(InputAltaTecnicoTelefono, "Inserte el telefono...");
    }//GEN-LAST:event_InputAltaTecnicoTelefonoFocusLost

    private void InputAltaTecnicoDNIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaTecnicoDNIFocusGained
        GainFocusStylishTextInput(InputAltaTecnicoDNI);
    }//GEN-LAST:event_InputAltaTecnicoDNIFocusGained

    private void InputAltaTecnicoDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaTecnicoDNIFocusLost
        LostFocusStylishTextInput(InputAltaTecnicoDNI, "Inserte el DNI...");
    }//GEN-LAST:event_InputAltaTecnicoDNIFocusLost

    private void InputAltaDirectivoApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaDirectivoApellidoFocusGained
        GainFocusStylishTextInput(InputAltaDirectivoApellido);
    }//GEN-LAST:event_InputAltaDirectivoApellidoFocusGained

    private void InputAltaDirectivoApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaDirectivoApellidoFocusLost
        LostFocusStylishTextInput(InputAltaDirectivoApellido, "Inserte el apellido...");
    }//GEN-LAST:event_InputAltaDirectivoApellidoFocusLost

    private void InputAltaDirectivoTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaDirectivoTelefonoFocusGained
        GainFocusStylishTextInput(InputAltaDirectivoTelefono);
    }//GEN-LAST:event_InputAltaDirectivoTelefonoFocusGained

    private void InputAltaDirectivoTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaDirectivoTelefonoFocusLost
        LostFocusStylishTextInput(InputAltaDirectivoTelefono, "Inserte el telefono...");
    }//GEN-LAST:event_InputAltaDirectivoTelefonoFocusLost

    private void InputAltaDirectivoDNIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaDirectivoDNIFocusGained
        GainFocusStylishTextInput(InputAltaDirectivoDNI);
    }//GEN-LAST:event_InputAltaDirectivoDNIFocusGained

    private void InputAltaDirectivoDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaDirectivoDNIFocusLost
        LostFocusStylishTextInput(InputAltaDirectivoDNI, "Inserte el DNI...");
    }//GEN-LAST:event_InputAltaDirectivoDNIFocusLost

    private void InputAltaDirectivoCargoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaDirectivoCargoFocusGained
        GainFocusStylishTextInput(InputAltaDirectivoCargo);
    }//GEN-LAST:event_InputAltaDirectivoCargoFocusGained

    private void InputAltaDirectivoCargoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaDirectivoCargoFocusLost
        LostFocusStylishTextInput(InputAltaDirectivoCargo, "Inserte el cargo...");
    }//GEN-LAST:event_InputAltaDirectivoCargoFocusLost

    private void InputAltaJugadorDNIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaJugadorDNIFocusGained
        GainFocusStylishTextInput(InputAltaJugadorDNI);
    }//GEN-LAST:event_InputAltaJugadorDNIFocusGained

    private void InputAltaJugadorDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputAltaJugadorDNIFocusLost
        LostFocusStylishTextInput(InputAltaJugadorDNI, "Inserte el DNI...");
    }//GEN-LAST:event_InputAltaJugadorDNIFocusLost

    private void forzarSoloNumero(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }

    private void stylishButtonEnter(JButton boton, Icon icon) {
        boton.setForeground(Color.white);
        boton.setIcon(icon);
    }

    private void stylishButtonEnter(JButton boton) {
        boton.setForeground(Color.white);
    }

    private void stylishButtonExit(JButton boton) {
        boton.setForeground(colorTexto);
        boton.setIcon(null);
    }

    private void GainFocusStylishTextInput(JTextField textInput) {
        //Chequea que el campo estaba vacio(mensaja predefinido)...Espero que ningun jugador se llame 'Inserte'...
        if (textInput.getText().contains("Inserte ")) {
            textInput.setText("");
            textInput.setForeground(Color.white);
        }

    }

    private void LostFocusStylishTextInput(JTextField textInput, String input) {
        if (textInput.getText().isEmpty()) {
            textInput.setText(input);
            textInput.setForeground(new Color(204, 204, 204));
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraTop;
    private javax.swing.JButton BtnCrearDirectivo;
    private javax.swing.JButton BtnCrearJugador;
    private javax.swing.JButton BtnCrearTecnico;
    private javax.swing.JButton BtnDarDeAltaAtras;
    private javax.swing.JButton BtnDarDeAltaPersona;
    private javax.swing.JButton BtnEliminarPersona;
    private javax.swing.JButton BtnGastos;
    private javax.swing.JButton BtnGestionarPlantilla;
    private javax.swing.JButton BtnHome;
    private javax.swing.JButton BtnImprimir;
    private javax.swing.JButton BtnJugarPartido;
    private javax.swing.JButton BtnModificarDatos;
    private javax.swing.JComboBox<Demarcacion> ComBoxDemarcacion;
    private javax.swing.JComboBox<Especialidad> ComboBoxTecnicoEspecialidad;
    private javax.swing.JComboBox<Puesto> ComboBoxTecnicoPuesto;
    private javax.swing.JPanel DarDeAltaWindow;
    private javax.swing.JPanel GestionWindow;
    private javax.swing.JPanel HomeWindow;
    private javax.swing.JTextField InputAltaDirectivoApellido;
    private javax.swing.JTextField InputAltaDirectivoCargo;
    private javax.swing.JTextField InputAltaDirectivoDNI;
    private javax.swing.JTextField InputAltaDirectivoNombre;
    private javax.swing.JTextField InputAltaDirectivoTelefono;
    private javax.swing.JTextField InputAltaJugadorApellido;
    private javax.swing.JTextField InputAltaJugadorDNI;
    private javax.swing.JTextField InputAltaJugadorEdad;
    private javax.swing.JTextField InputAltaJugadorNombre;
    private javax.swing.JTextField InputAltaJugadorTelefono;
    private javax.swing.JTextField InputAltaJugadorValor;
    private javax.swing.JTextField InputAltaTecnicoApellido;
    private javax.swing.JTextField InputAltaTecnicoDNI;
    private javax.swing.JTextField InputAltaTecnicoNombre;
    private javax.swing.JTextField InputAltaTecnicoTelefono;
    private javax.swing.JPanel PanelAltaDirectivo;
    private javax.swing.JPanel PanelAltaJugador;
    private javax.swing.JPanel PanelAltaTecnico;
    private javax.swing.JScrollPane PanelGestionPersonas;
    private javax.swing.JScrollPane PanelPlantilla;
    private javax.swing.JPanel PanelRaiz;
    private javax.swing.JPanel Panel_RightSide;
    private javax.swing.JSeparator Separador;
    private javax.swing.JSeparator Separador1;
    private javax.swing.JTabbedPane TabbedDarDeAlta;
    private javax.swing.JTable TablaContenidoPlantilla;
    private javax.swing.JTable TablaGestionPersonas;
    private javax.swing.JLabel Text_DarDeAlta;
    private javax.swing.JLabel Text_PlantillaActual;
    private javax.swing.JLabel Text_Titulo;
    private javax.swing.JLabel TextoAltaDirectivoApellido;
    private javax.swing.JLabel TextoAltaDirectivoCargo;
    private javax.swing.JLabel TextoAltaDirectivoDNI;
    private javax.swing.JLabel TextoAltaDirectivoNombre;
    private javax.swing.JLabel TextoAltaDirectivoTelefono;
    private javax.swing.JLabel TextoAltaJugadorApellido;
    private javax.swing.JLabel TextoAltaJugadorDNI;
    private javax.swing.JLabel TextoAltaJugadorDNI1;
    private javax.swing.JLabel TextoAltaJugadorDemarcacion;
    private javax.swing.JLabel TextoAltaJugadorEdad;
    private javax.swing.JLabel TextoAltaJugadorEstadoFisico;
    private javax.swing.JLabel TextoAltaJugadorNombre;
    private javax.swing.JLabel TextoAltaJugadorTelefono;
    private javax.swing.JLabel TextoAltaJugadorValor;
    private javax.swing.JLabel TextoAltaJugadorValor1;
    private javax.swing.JLabel TextoAltaTecnicoApellido;
    private javax.swing.JLabel TextoAltaTecnicoDNI;
    private javax.swing.JLabel TextoAltaTecnicoNombre;
    private javax.swing.JLabel TextoAltaTecnicoTelefono;
    private javax.swing.JToggleButton ToggleEstadoFisico;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables

    public JPanel getHomeWindow() {
        return HomeWindow;
    }

    public JPanel getPanelRaiz() {
        return PanelRaiz;
    }

    public JPanel getGestionWindow() {
        return GestionWindow;
    }

    public JLabel getText_PlantillaActual() {
        return Text_PlantillaActual;
    }

    public JButton getBtnGastos() {
        return BtnGastos;
    }

    public JButton getBtnGestionarPlantilla() {
        return BtnGestionarPlantilla;
    }

    public JButton getBtnImprimir() {
        return BtnImprimir;
    }

    public JButton getBtnJugarPartido() {
        return BtnJugarPartido;
    }

    public JScrollPane getPanelPlantilla() {
        return PanelPlantilla;
    }

    public JTable getTablaContenidoPlantilla() {
        return TablaContenidoPlantilla;
    }

    public JButton getBtnHome() {
        return BtnHome;
    }

    public JTable getTablaGestionPersonas() {
        return TablaGestionPersonas;
    }

    public JButton getBtnEliminarPersona() {
        return BtnEliminarPersona;
    }

    public JButton getBtnDarDeAltaPersona() {
        return BtnDarDeAltaPersona;
    }

    public JComboBox<Especialidad> getComboBoxTecnicoEspecialidad() {
        return ComboBoxTecnicoEspecialidad;
    }

    public JComboBox<Puesto> getComboBoxTecnicoPuesto() {
        return ComboBoxTecnicoPuesto;
    }

    public JComboBox<Demarcacion> getComBoxDemarcacion() {
        return ComBoxDemarcacion;
    }

    public JToggleButton getToggleEstadoFisico() {
        return ToggleEstadoFisico;
    }

    public JButton getBtnDarDeAltaAtras() {
        return BtnDarDeAltaAtras;
    }

    public JButton getBtnCrearDirectivo() {
        return BtnCrearDirectivo;
    }

    public JButton getBtnCrearJugador() {
        return BtnCrearJugador;
    }

    public JButton getBtnCrearTecnico() {
        return BtnCrearTecnico;
    }

    public JTextField getInputAltaDirectivoApellido() {
        return InputAltaDirectivoApellido;
    }

    public JTextField getInputAltaDirectivoCargo() {
        return InputAltaDirectivoCargo;
    }

    public JTextField getInputAltaDirectivoDNI() {
        return InputAltaDirectivoDNI;
    }

    public JTextField getInputAltaDirectivoNombre() {
        return InputAltaDirectivoNombre;
    }

    public JTextField getInputAltaDirectivoTelefono() {
        return InputAltaDirectivoTelefono;
    }

    public JTextField getInputAltaJugadorApellido() {
        return InputAltaJugadorApellido;
    }

    public JTextField getInputAltaJugadorDNI() {
        return InputAltaJugadorDNI;
    }

    public JTextField getInputAltaJugadorEdad() {
        return InputAltaJugadorEdad;
    }

    public JTextField getInputAltaJugadorNombre() {
        return InputAltaJugadorNombre;
    }

    public JTextField getInputAltaJugadorTelefono() {
        return InputAltaJugadorTelefono;
    }

    public JTextField getInputAltaJugadorValor() {
        return InputAltaJugadorValor;
    }

    public JTextField getInputAltaTecnicoApellido() {
        return InputAltaTecnicoApellido;
    }

    public JTextField getInputAltaTecnicoDNI() {
        return InputAltaTecnicoDNI;
    }

    public JTextField getInputAltaTecnicoTelefono() {
        return InputAltaTecnicoTelefono;
    }

}
